# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1297540344);
user_pref("app.update.lastUpdateTime.background-update-timer", 1297540140);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1297539813);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1297539988);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1297539585);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1297618179);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.migration.version", 1);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.13");
user_pref("extensions.enabledItems", "{AB2CE124-6272-4b12-94A9-7303C7397BD1}:4.2.0.5198,{CAFEEFAC-0016-0000-0018-ABCDEFFEDCBA}:6.0.18,{CAFEEFAC-0016-0000-0020-ABCDEFFEDCBA}:6.0.20,{CAFEEFAC-0016-0000-0021-ABCDEFFEDCBA}:6.0.21,{CAFEEFAC-0016-0000-0022-ABCDEFFEDCBA}:6.0.22,{CAFEEFAC-0016-0000-0023-ABCDEFFEDCBA}:6.0.23,{ABDE892B-13A8-4d1b-88E6-365A6E755758}:14.0.2,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.13");
user_pref("extensions.lastAppVersion", "3.6.13");
user_pref("idle.lastDailyNotification", 1297570824);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.last_vacuum", 1297570824);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1300131098);
user_pref("browser.startup.homepage", "http://xfinity.comcast.net/?cid=insDate29042012");
user_pref("browser.startup.page", 1);
user_pref("extensions.autoDisableScopes", 0);
